## This file pulls the docker and builds the image and run the test cases.
version: '3.3'

services:

    server1:
        build: .
        ports:
          - "5000:5000"
        expose:
          - 5000
        command: python3 server.py --id 1 --host 127.0.0.1 --port 5000



    server2:
        build: .
        ports:
          - "5001:5001"
        expose:
          - 5001
        command: python3 server.py --id 2 --host 127.0.0.1 --port 5001


    server3:
        build: .
        ports:
          - "5002:5002"
        expose:
          - 5002
        command: python3 server.py --id 3 --host 127.0.0.1 --port 5002


    server4:
        build: .
        ports:
          - "5003:5003"
        expose:
          - 5003
        command: python3 server.py --id 4 --host 127.0.0.1 --port 5003


    server5:
        build: .
        ports:
          - "5004:5004"
        expose:
          - 5004
        command:  python3 server.py --id 5 --host 127.0.0.1 --port 5004




